# Generated by Django 3.2.3 on 2021-07-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/search?q=default+food+image&sxsrf=ALeKk02WWvJU9ppwQ3WoS4RQ5BItGLNfdg:1626959230423&tbm=isch&source=iu&ictx=1&fir=L0HD2AKXXoGxjM%252CmknM6elDrlUQtM%252C_&vet=1&usg=AI4_-kTby_LloZPZa6kTBavWUio419RDyQ&sa=X&ved=2ahUKEwjMs_i33_bxAhUx7XMBHQJVAN0Q9QF6BAgPEAE#imgrc=L0HD2AKXXoGxjMc', max_length=500),
        ),
    ]
