# Generated by Django 3.2.3 on 2021-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_item_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures'),
        ),
    ]
