# Generated by Django 3.2.3 on 2021-07-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='https://media.istockphoto.com/vectors/illustration-icon-with-the-concept-of-food-donation-vector-id951697932?k=6&m=951697932&s=612x612&w=0&h=cewzX5-oehPnBVufvbWBLbRfvRA_Bh0OouWgHZjzwH0=', max_length=500, upload_to=''),
        ),
    ]
